dbt_leantech_airbnb_project:
  outputs:
    dev:
      dbname: "{{ env_var('PG_DATABASE_NM') }}"
      host: "{{ env_var('PG_HOST') }}"
      user: "{{ env_var('PG_USER') }}"
      pass: "{{ env_var('PG_PASSWORD') }}"
      port: 5432
      schema: "{{ env_var('PG_SCHEMA_BRONZE') }}"
      threads: 1
      type: postgres
    silver:
      dbname: "{{ env_var('PG_DATABASE_NM') }}"
      host: "{{ env_var('PG_HOST') }}"
      user: "{{ env_var('PG_USER') }}"
      pass: "{{ env_var('PG_PASSWORD') }}"
      port: 5432
      schema: "{{ env_var('PG_SCHEMA_SILVER') }}"
      threads: 1
      type: postgres
    gold:
      dbname: "{{ env_var('PG_DATABASE_NM') }}"
      host: "{{ env_var('PG_HOST') }}"
      user: "{{ env_var('PG_USER') }}"
      pass: "{{ env_var('PG_PASSWORD') }}"
      port: 5432
      schema: "{{ env_var('PG_SCHEMA_GOLD') }}"
      threads: 1
      type: postgres
  target: dev
