dbt_leantech_airbnb_project:
  outputs:
    dev:
      dbname: leantech_prjct_airbnb_db
      host: localhost
      pass: root
      port: 5432
      schema: sch_bronze_airbnb
      threads: 1
      type: postgres
      user: root
  target: dev
